//Local Host: 
### All
GET http://localhost:8080/contacts

### Naesalia
GET http://localhost:8080/contacts/6324c52fc7489f61e6063f58 

### Maethoriel
GET http://localhost:8080/contacts/6324c58ec7489f61e6063f59

### Kaikani
GET http://localhost:8080/contacts/6324c655c7489f61e6063f5a

### Shawn
GET http://localhost:8080/contacts/6324c6b1c7489f61e6063f5b

### Riaxa
GET http://localhost:8080/contacts/6324c731c7489f61e6063f5c

###Add a friend
POST http://localhost:8080/contacts 
Content-Type: application/json

{"firstname": "DeleteMeLocally!", "lastname": "Imlocal", "email": "removemealready@goodbye.go", "favColor": "mud", "bday": "1977-08-12T02:00:00.000Z"}
### {"firstname": "Méren", "lastname": "Noldotor", "email": "futurechiefess@lamond.com", "favColor": "orange", "bday": "2002-04-25T02:00:00.000Z"}
### {
###     "firstname": "Béren",
###     "lastname": "Kingsail",
###     "email": "wishisail@lamond.com",
###     "favColor": "red",
###     "bday": "1995-07-25T02:00:00.000Z"
###   }

###Update data
PUT http://localhost:8080/contacts/632e45d42634ce1695e47ff0
Content-Type: application/json

{
    "firstname": "Béren",
    "lastname": "Kingsail",
    "email": "berenseal@lamond.com",
    "favColor": "red",
    "bday": "1995-07-25T02:00:00.000Z"
  }

### {"firstname": "Test", "lastname": "Dude", "email": "iamawesome@trivolcano.com", "favColor": "grey", "bday": "2000-01-10T03:00:00.000Z"}
### {"firstname": "Elethial", "lastname": "Noraskosen", "email": "healertwin@taurenor.com", "favColor": "yellow", "bday": "2000-06-01T04:00:00.000Z"}

###Delete 
DELETE http://localhost:8080/contacts/632e2dbc417a8d3fc267b591 HTTP/1.1


//Render
### All
GET https://tauriel341.onrender.com/contacts

### Maethoriel
GET https://tauriel341.onrender.com/contacts/6324c58ec7489f61e6063f59

### Kaikani
GET https://tauriel341.onrender.com/contacts/6324c655c7489f61e6063f5a

###Add with Render
POST http://tauriel341.onrender.com/contacts 
Content-Type: application/json

{"firstname": "Faran", "lastname": " ", "email": "ibelongtolight@wizelf.com", "favColor": "light grey", "bday": "2000-03-13T02:00:00.000Z"}
### {"firstname": "DeleteMe!", "lastname": "Idonotbelong", "email": "opleasedeleteme@remove.go", "favColor": "red and black", "bday": "1977-02-28T02:00:00.000Z"}


###Update with Render 
PUT http://tauriel341.onrender.com/contacts/632b94a8358f68f039df78fc 
Content-Type: application/json

{"firstname": "DeleteMe!", "lastname": "Idonotbelong", "email": "opleasedeleteme@remove.go", "favColor": "grey and white", "bday": "1977-02-28T02:00:00.000Z"}


###Delete with Render
DELETE http://localhost:8080/contacts/632b94a8358f68f039df78fc HTTP/1.1
